// frontend/stack-underflow_vue/src/components/Login.vue
<script setup lang="ts">
import { ref } from "vue";
import { useRouter } from "vue-router";
import { useI18n } from "vue-i18n";
import { storeToRefs } from "pinia";
import { useAuthStore } from "@/store/auth";

const router = useRouter();
const { t } = useI18n();
const authStore = useAuthStore();
const { login } = authStore;

const username = ref("");
const password = ref("");

const handleSubmit = () => {
  if (username.value.trim()) {
    login(username.value, password.value);
    router.push("/");
  }
};
</script>

<template>
  <div class="login-container">
    <div class="login-card">
      <h1 class="login-title">{{ t("login.title") }}</h1>
      <p class="login-subtitle">{{ t("login.subtitle") }}</p>
      <form @submit.prevent="handleSubmit" class="login-form">
        <div class="form-group">
          <label for="username">{{ t("login.usernameLabel") }}</label>
          <input
            type="text"
            id="username"
            v-model="username"
            :placeholder="t('login.usernamePlaceholder')"
            required
          />
        </div>
        <div class="form-group">
          <label for="password">{{ t("login.passwordLabel") }}</label>
          <input
            type="password"
            id="password"
            v-model="password"
            :placeholder="t('login.passwordPlaceholder')"
            required
          />
        </div>
        <button type="submit" class="login-button">
          {{ t("login.loginButton") }}
        </button>
      </form>
      <p class="login-note">
        {{ t("login.note") }}
      </p>
    </div>
  </div>
</template>

// frontend/stack-underflow/src/components/Login.tsx
import { useState } from "react";
import { useAuth } from "#src/store/AuthContext";

export function Login() {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const { login } = useAuth();

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (username.trim()) {
      login(username, password);
    }
  };

  return (
    <div className="login-container">
      <div className="login-card">
        <h1 className="login-title">Stack Underflow</h1>
        <p className="login-subtitle">Q&A Platform</p>
        <form onSubmit={handleSubmit} className="login-form">
          <div className="form-group">
            <label htmlFor="username">Username</label>
            <input
              type="text"
              id="username"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              placeholder="Enter any username"
              required
            />
          </div>
          <div className="form-group">
            <label htmlFor="password">Password</label>
            <input
              type="password"
              id="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              placeholder="Enter any password"
              required
            />
          </div>
          <button type="submit" className="login-button">
            Login
          </button>
        </form>
        <p className="login-note">
          Note: This is a mock login. Any username/password will work.
        </p>
      </div>
    </div>
  );
}
