// frontend/stack-underflow_angular/src/app/components/create-question/create-question.component.ts
import { Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { QuestionsService } from '../../services/questions.service';
import { I18nService } from '../../services/i18n.service';

@Component({
  selector: 'app-create-question',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './create-question.component.html',
  styleUrls: ['./create-question.component.css']
})
export class CreateQuestionComponent {
  private router = inject(Router);
  authService = inject(AuthService);
  questionsService = inject(QuestionsService);
  i18nService = inject(I18nService);

  title = '';
  description = '';
  submitting = signal(false);
  error = signal('');

  get t(): (key: string) => string {
    return (key: string) => this.i18nService.t(key);
  }

  async handleSubmit(): Promise<void> {
    if (!this.authService.isAuthenticated) {
      this.error.set(this.t('createQuestion.error.notLoggedIn'));
      return;
    }

    this.submitting.set(true);
    this.error.set('');

    try {
      const user = this.authService.user;
      if (user) {
        const question = await this.questionsService.createQuestion(
          this.title,
          this.description,
          user.id,
          user.username
        );
        if (question) {
          this.router.navigate(['/questions', question.id]);
        }
      }
    } catch (err) {
      this.error.set(err instanceof Error ? err.message : 'Failed to create question');
    } finally {
      this.submitting.set(false);
    }
  }
}

@if (!authService.isAuthenticated) {
  <div class="error-message">{{ t('createQuestion.error.notLoggedIn') }}</div>
} @else {
  @if (error()) {
    <div class="error-message">{{ error() }}</div>
  }
  <form (ngSubmit)="handleSubmit()" class="question-form">
    <div class="form-group">
      <label for="title">{{ t('createQuestion.titleLabel') }}</label>
      <input
        type="text"
        id="title"
        [(ngModel)]="title"
        name="title"
        [placeholder]="t('createQuestion.titlePlaceholder')"
        required
      />
      <span class="form-hint">{{ t('createQuestion.titleHint') }}</span>
    </div>
    <div class="form-group">
      <label for="description">{{ t('createQuestion.descriptionLabel') }}</label>
      <textarea
        id="description"
        [(ngModel)]="description"
        name="description"
        [placeholder]="t('createQuestion.descriptionPlaceholder')"
        rows="5"
        required
      ></textarea>
      <span class="form-hint">{{ t('createQuestion.descriptionHint') }}</span>
    </div>
    <div class="form-actions">
      <button type="submit" class="btn-primary" [disabled]="submitting()">
        {{ submitting() ? t('createQuestion.submitting') : t('createQuestion.postQuestion') }}
      </button>
    </div>
  </form>
}

// frontend/stack-underflow_vue/src/components/CreateQuestion.vue
<script setup lang="ts">
import { ref } from "vue";
import { useRouter } from "vue-router";
import { useI18n } from "vue-i18n";
import { storeToRefs } from "pinia";
import { useAuthStore } from "@/store/auth";
import { createQuestion } from "@/api/questions";
import type { ApiError } from "@/api/types";

const router = useRouter();
const { t } = useI18n();
const authStore = useAuthStore();
const { user } = storeToRefs(authStore);

const title = ref("");
const description = ref("");
const error = ref<string | null>(null);
const isSubmitting = ref(false);

const handleSubmit = async () => {
  error.value = null;

  if (!user.value) {
    error.value = t("createQuestion.error.notLoggedIn");
    return;
  }

  isSubmitting.value = true;

  try {
    await createQuestion({
      title: title.value,
      description: description.value,
      userId: user.value.id,
      username: user.value.username,
    });
    router.push("/");
  } catch (err: unknown) {
    const apiError = err as ApiError;
    const errorMessages: Record<string, string> = {
      TITLE_REQUIRED: t("createQuestion.error.titleRequired"),
      TITLE_TOO_SHORT: t("createQuestion.error.titleTooShort"),
      TITLE_TOO_LONG: t("createQuestion.error.titleTooLong"),
      DESCRIPTION_REQUIRED: t("createQuestion.error.descriptionRequired"),
      DESCRIPTION_TOO_SHORT: t("createQuestion.error.descriptionTooShort"),
      DESCRIPTION_TOO_LONG: t("createQuestion.error.descriptionTooLong"),
    };

    error.value = errorMessages[apiError.code] || apiError.message;

    console.error("[CreateQuestion] Error:", {
      code: apiError.code,
      message: apiError.message,
      details: apiError.details,
      timestamp: new Date().toISOString(),
    });
  } finally {
    isSubmitting.value = false;
  }
};

const handleCancel = () => {
  router.push("/");
};
</script>

<template>
  <div class="create-question">
    <div class="create-question-card">
      <h1>{{ t("createQuestion.title") }}</h1>
      <div v-if="error" class="error-message" role="alert">
        {{ error }}
      </div>
      <form @submit.prevent="handleSubmit" class="question-form">
        <div class="form-group">
          <label for="title">{{ t("createQuestion.titleLabel") }}</label>
          <input
            id="title"
            type="text"
            v-model="title"
            :placeholder="t('createQuestion.titlePlaceholder')"
            :disabled="isSubmitting"
            required
          />
          <small class="form-hint">
            {{ t("createQuestion.titleHint") }}
          </small>
        </div>
        <div class="form-group">
          <label for="description">{{ t("createQuestion.descriptionLabel") }}</label>
          <textarea
            id="description"
            v-model="description"
            :placeholder="t('createQuestion.descriptionPlaceholder')"
            rows="6"
            :disabled="isSubmitting"
            required
          />
          <small class="form-hint">
            {{ t("createQuestion.descriptionHint") }}
          </small>
        </div>
        <div class="form-actions">
          <button
            type="submit"
            class="btn-primary"
            :disabled="isSubmitting"
          >
            <template v-if="isSubmitting">
              {{ t("createQuestion.submitting") }}
            </template>
            <template v-else>
              {{ t("createQuestion.postQuestion") }}
            </template>
          </button>
          <button
            type="button"
            @click="handleCancel"
            class="btn-secondary"
            :disabled="isSubmitting"
          >
            {{ t("createQuestion.cancel") }}
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
