// frontend with datastore/stack-underflow/src/components/Header.tsx
import { Link } from "react-router-dom";
import { useAuth } from "#src/store/AuthContext";
import { useTranslation } from "react-i18next";

export function Header() {
  const { user, logout, isAuthenticated } = useAuth();
  const { t, i18n } = useTranslation();

  const changeLanguage = (lng: string) => {
    i18n.changeLanguage(lng);
  };

  return (
    <header className="header">
      <div className="header-content">
        <Link to="/" className="logo">
          {t("header.logo")}
        </Link>
        <nav className="nav">
          <Link to="/" className="nav-link">
            {t("header.questions")}
          </Link>
          {isAuthenticated && (
            <Link to="/questions/new" className="nav-link">
              {t("header.askQuestion")}
            </Link>
          )}
        </nav>
        <div className="user-menu">
          <div className="language-switcher">
            <button
              onClick={() => changeLanguage("en")}
              className={`lang-btn ${i18n.language === "en" ? "active" : ""}`}
            >
              EN
            </button>
            <button
              onClick={() => changeLanguage("id")}
              className={`lang-btn ${i18n.language === "id" ? "active" : ""}`}
            >
              ID
            </button>
          </div>
          {isAuthenticated ? (
            <>
              <span className="username">{user?.username}</span>
              <button onClick={logout} className="btn-logout">
                {t("header.logout")}
              </button>
            </>
          ) : (
            <div className="auth-buttons">
              <Link to="/login" className="btn-login">
                {t("header.login")}
              </Link>
              <Link to="/signup" className="btn-signup">
                {t("header.signup")}
              </Link>
            </div>
          )}
        </div>
      </div>
    </header>
  );
}

// frontend/stack-underflow_vue/src/components/Header.vue
<script setup lang="ts">
import { useRouter } from "vue-router";
import { useI18n } from "vue-i18n";
import { storeToRefs } from "pinia";
import { useAuthStore } from "@/store/auth";

const router = useRouter();
const { t, locale } = useI18n();
const authStore = useAuthStore();
const { user, isAuthenticated } = storeToRefs(authStore);
const { logout } = authStore;

const changeLanguage = (lng: string) => {
  locale.value = lng;
};

const handleLogout = () => {
  logout();
  router.push("/");
};
</script>

<template>
  <header class="header">
    <div class="header-content">
      <router-link to="/" class="logo">
        {{ t("header.logo") }}
      </router-link>
      <nav class="nav">
        <router-link to="/" class="nav-link">
          {{ t("header.questions") }}
        </router-link>
        <router-link v-if="isAuthenticated" to="/questions/new" class="nav-link">
          {{ t("header.askQuestion") }}
        </router-link>
      </nav>
      <div class="user-menu">
        <div class="language-switcher">
          <button
            @click="changeLanguage('en')"
            :class="['lang-btn', { active: locale === 'en' }]"
          >
            EN
          </button>
          <button
            @click="changeLanguage('id')"
            :class="['lang-btn', { active: locale === 'id' }]"
          >
            ID
          </button>
        </div>
        <template v-if="isAuthenticated">
          <span class="username">{{ user?.username }}</span>
          <button @click="handleLogout" class="btn-logout">
            {{ t("header.logout") }}
          </button>
        </template>
        <template v-else>
          <div class="auth-buttons">
            <router-link to="/login" class="btn-login">
              {{ t("header.login") }}
            </router-link>
            <router-link to="/signup" class="btn-signup">
              {{ t("header.signup") }}
            </router-link>
          </div>
        </template>
      </div>
    </div>
  </header>
</template>
