// frontend/stack-underflow_angular/src/app/components/header/header.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { I18nService } from '../../services/i18n.service';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [CommonModule, RouterLink, RouterLinkActive],
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent {
  authService = inject(AuthService);
  i18nService = inject(I18nService);

  get t(): (key: string) => string {
    return (key: string) => this.i18nService.t(key);
  }

  changeLanguage(lng: string): void {
    this.i18nService.setLocale(lng);
  }

  logout(): void {
    this.authService.logout();
  }
}

<header class="header">
  <div class="header-content">
    <a routerLink="/" class="logo">{{ t('header.logo') }}</a>
    <nav class="nav">
      <a routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{ exact: true }" class="nav-link">
        {{ t('header.questions') }}
      </a>
      @if (authService.isAuthenticated) {
        <a routerLink="/questions/new" class="nav-link">
          {{ t('header.askQuestion') }}
        </a>
      }
    </nav>
    <div class="user-menu">
      <div class="language-switcher">
        <button
          type="button"
          (click)="changeLanguage('en')"
          [class]="['lang-btn', { active: i18nService.locale === 'en' }]"
        >
          EN
        </button>
        <button
          type="button"
          (click)="changeLanguage('id')"
          [class]="['lang-btn', { active: i18nService.locale === 'id' }]"
        >
          ID
        </button>
      </div>
      @if (authService.isAuthenticated && authService.user; as user) {
        <span class="username">{{ user.username }}</span>
        <button type="button" (click)="logout()" class="btn-logout">
          {{ t('header.logout') }}
        </button>
      } @else {
        <div class="auth-buttons">
          <a routerLink="/login" class="btn-login">{{ t('header.login') }}</a>
          <a routerLink="/signup" class="btn-signup">{{ t('header.signup') }}</a>
        </div>
      }
    </div>
  </div>
</header>

// frontend with datastore/stack-underflow/src/components/Header.tsx
import { Link } from "react-router-dom";
import { useAuth } from "#src/store/AuthContext";
import { useTranslation } from "react-i18next";

export function Header() {
  const { user, logout, isAuthenticated } = useAuth();
  const { t, i18n } = useTranslation();

  const changeLanguage = (lng: string) => {
    i18n.changeLanguage(lng);
  };

  return (
    <header className="header">
      <div className="header-content">
        <Link to="/" className="logo">
          {t("header.logo")}
        </Link>
        <nav className="nav">
          <Link to="/" className="nav-link">
            {t("header.questions")}
          </Link>
          {isAuthenticated && (
            <Link to="/questions/new" className="nav-link">
              {t("header.askQuestion")}
            </Link>
          )}
        </nav>
        <div className="user-menu">
          <div className="language-switcher">
            <button
              onClick={() => changeLanguage("en")}
              className={`lang-btn ${i18n.language === "en" ? "active" : ""}`}
            >
              EN
            </button>
            <button
              onClick={() => changeLanguage("id")}
              className={`lang-btn ${i18n.language === "id" ? "active" : ""}`}
            >
              ID
            </button>
          </div>
          {isAuthenticated ? (
            <>
              <span className="username">{user?.username}</span>
              <button onClick={logout} className="btn-logout">
                {t("header.logout")}
              </button>
            </>
          ) : (
            <div className="auth-buttons">
              <Link to="/login" className="btn-login">
                {t("header.login")}
              </Link>
              <Link to="/signup" className="btn-signup">
                {t("header.signup")}
              </Link>
            </div>
          )}
        </div>
      </div>
    </header>
  );
}
